name: macOS investigations

on:
  push:
    branches:
      - macos-investigations/*

jobs:
  macos-tests:
    timeout-minutes: 30
    runs-on: macos-latest
    strategy:
      matrix:
        jdk-version: [ 17 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk-version }}

      # Docker is not installed on GitHub's MacOS hosted workers due to licensing issues
      # (and it's necessary to run Autobahn tests)
      - name: Install docker and docker-compose (missing on MacOS)
        uses: ./.github/actions/setup-docker-macos

      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk${{ matrix.jdk-version }}-macos-investigations
          arguments: allTests

      - name: Upload Autobahn reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: autobahn-reports-${{ runner.os }}-jdk${{ matrix.jdk-version }}
          path: autobahn-tests/build/autobahn/reports/clients
